service: api-gateway-example

frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action: "secretsmanager:GetSecretValue"
      Resource: !Ref DataDogSM
    # uncomment the next lines only if you choose dynamodb as db
#    - Effect: Allow
#      Action: "dynamodb:*"
#      Resource: !Ref DynamoTable
  environment:
    CLOUD: "true"
    DB: ${file(./credentials.json):db}
    DB_URI: ${file(./credentials.json):mongo_url}

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  create:
    handler: bin/create
    events:
      - httpApi:
          path: /v1/todos
          method: post

  delete:
    handler: bin/delete
    events:
      - httpApi:
          path: /v1/todos
          method: delete

  retrieve:
    handler: bin/get
    events:
      - httpApi:
          path: /v1/todos/{id}
          method: get

  list:
    handler: bin/list
    events:
      - httpApi:
          path: /v1/todos
          method: get

  update:
    handler: bin/update
    events:
      - httpApi:
          path: /v1/todos
          method: patch

resources:
  Resources:
    DataDogSM:
      Type: AWS::SecretsManager::Secret
      Properties:
        Name: DatadogKey
        SecretString: ${file(./credentials.json):datadog.api_key}
    # uncomment the next lines only if you choose dynamodb as db
#    DynamoTable:
#      Type: AWS::DynamoDB::Table
#      Properties:
#        TableName: "todos"
#        BillingMode: PAY_PER_REQUEST
#        AttributeDefinitions:
#          - AttributeName: "Id"
#            AttributeType: "N"
#        KeySchema:
#          - AttributeName: "Id"
#            KeyType: "HASH"
#        GlobalSecondaryIndexes:
#          - IndexName: "Id-Index"
#            KeySchema:
#              - AttributeName: "Id"
#                KeyType: "HASH"
#            Projection:
#              ProjectionType: "ALL"
#            ProvisionedThroughput:
#              ReadCapacityUnits: 5
#              WriteCapacityUnits: 5
#        ProvisionedThroughput:
#          ReadCapacityUnits: 5
#          WriteCapacityUnits: 5
  Outputs:
    DataDogArn:
      Description: "Datadog Arn"
      Value: !Ref DataDogSM

custom:
  datadog:
    site: ${file(./credentials.json):datadog.site}
    apiKeySecretArn: !Ref DataDogSM

plugins:
  - serverless-plugin-datadog
